apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "videor.fullname" . }}-config
data:
  RAILS_ENV: {{ .Values.env.RAILS_ENV | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
  AWS_REGION: {{ .Values.env.AWS_REGION | quote }}
  STORAGE_HOST_ALLOWLIST: {{ .Values.env.STORAGE_HOST_ALLOWLIST | quote }}
