apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videor.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "videor.name" . }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "videor.name" . }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "videor.name" . }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "videor.fullname" . }}-config
            - secretRef:
                name: {{ include "videor.fullname" . }}-secrets
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "videor.fullname" . }}-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "videor.name" . }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
