{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "videor.fullname" . }}-redis
spec:
  selector:
    app.kubernetes.io/name: {{ include "videor.name" . }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videor.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "videor.name" . }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "videor.name" . }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "videor.name" . }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
{{- end }}
