apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videor.fullname" . }}-secrets
type: Opaque
stringData:
  RAILS_MASTER_KEY: {{ .Values.secrets.railsMasterKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  VIDEO_JOBS_BUCKET: {{ .Values.secrets.videoJobsBucket | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
